# 基础镜像， cuda为11.0，ubuntu18.04
FROM image.rsaicp.com/base/cuda:11.0-cudnn8-runtime-ubuntu18.04

# 配置程序依赖环境
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         curl \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 \
         python3-pip && \
     rm -rf /var/lib/apt/lists/*

# 安装torch
RUN pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

RUN pip3 install matplotlib>=3.2.2
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
RUN pip3 install 
# 将程序复制到容器内的/work路径下
COPY .  /work

# 容器启动命令
CMD ["python3", "-u", "/work/main.py"]

